version: '1.0'
services:
    jupyter-notebook:
        build:.
        port:
            - "8888:8888"
        deploy:
            resources:
                devices:
                    - driver: nvidia
                      count: 1
                      capabilities: [gpu]
		